# config/storage.yml
cloudinary:
  service: Cloudinary
  folder: <%= Rails.env %>

# config/environments/development.rb
# âš ï¸Â MAKE SURE YOU REMOVE THE EXISTING ONE
# config.active_storage.service = :local
# Add this one ğŸ‘‡
config.active_storage.service = :cloudinary

# config/environments/production.rb
# âš ï¸Â MAKE SURE YOU REMOVE THE EXISTING ONE
# config.active_storage.service = :local
# Add this one ğŸ‘‡
config.active_storage.service = :cloudinary
